name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter

  flutter_timezone: ^1.0.4
  http: ^0.13.4
  path_provider: ^2.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - icons/

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"
